services:
  backend:
    profiles: ["app"]            
    build:
      context: ./backend
    environment:
      - DATABASE_URL=sqlite:////app/data/data.db
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
      - ./backend/data:/app/data
    networks:
      - app-network

  frontend:
    profiles: ["app"]            
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  jenkins:
    profiles: ["jenkins"]       
    build:
      context: ./jenkins
      args:
        DOCKER_GID: ${DOCKER_GID}    
    ports:
      - "8081:8080"
      # - "50000:50000"   # opcional: agentes JNLP
    environment:
      - TZ=${TZ}
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/bootstrap.groovy:/usr/share/jenkins/ref/init.groovy.d/bootstrap.groovy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_home:
