services:
  backend:
    command: >
      sh -c "pytest -q"
    volumes: []
    environment:
      - ENV=ci

  frontend:
    command: >
      sh -c "npm install && npm run test -- --watch=false --browsers=ChromeHeadless"
    volumes: []
    environment:
      - ENV=ci
